// data/project-templates/vue/files/src/App.vue
<script setup>
import { ref } from "vue";

const count = ref(0);
</script>

<template>
  <main class="app">
    <h1>欢迎来到 AI Studio（Vue）</h1>
    <p>这是一个 Vue 模板项目。</p>
    <button @click="count += 1">Count: {{ count }}</button>
  </main>
</template>

<style scoped>
.app {
  font-family: "Sora", sans-serif;
  padding: 48px;
  color: #1f2937;
}
button {
  margin-top: 12px;
  border: 0;
  border-radius: 10px;
  padding: 10px 14px;
  background: #111827;
  color: #fff;
  cursor: pointer;
}
</style>

// data/project-templates/vite-react/files/src/App.jsx
import { useState } from "react";

export default function App() {
  const [count, setCount] = useState(0);
  return (
    <main style={{ fontFamily: "Sora, sans-serif", padding: 48 }}>
      <h1>欢迎来到 AI Studio（Vite + React）</h1>
      <p>这是一个 Vite 风格 React 模板项目。</p>
      <button onClick={() => setCount((c) => c + 1)}>Count: {count}</button>
    </main>
  );
}
